% Script file: 
%   draw3DSurf.m

% Purpose: This function draw the prediction surface and the MSE surface
% given the evaluated Stochastic Kriging model.

% Record of revisions
%   Date        Programmer      Description of change
%   ========    ==========      =========================================
%   11/07/25    hieutd          Original code.

% Define variables:
%   SKmodel: text string - name of the file containing the SK model params

function f = draw3DSurf(SKmodel, maxX, minX, X, Y)

[k d] = size(minX);
if (d == 1)
    minX = reshape(minX, d, k);
    maxX = reshape(maxX, d, k);
end
[k d] = size(X);

K = 50; % K^2 is the number of prediction points, which will be generated by meshgrid function
[Xp Yp] = meshgrid(minX(1):((maxX(1) - minX(1))/(K-1)):maxX(1),...
    minX(2):((maxX(2) - minX(2))/(K-1)):maxX(2));
XK = [reshape(Xp, [K^2 1]) reshape(Yp, [K^2 1])];

[SK_gau MSE] = predictCal(XK, SKmodel);
 
% reshape the results into graph-compatible form
SKp = reshape(SK_gau, [K K]);
msep = reshape(MSE, [K K]);

% draw all graphs

subplot(1, 2, 1);
surf(Xp, Yp, SKp);
shading flat;
hold on;
scatter3(X(1:k,1), X(1:k,2), Y, 'filled','MarkerFaceColor','black');
title('SK prediction surface','FontWeight', 'bold');
colorbar;

subplot(1, 2, 2);
surface(Xp, Yp, msep);
title('SK surface with regard to predicted MSE','FontWeight', 'bold');
colorbar;

f = {0};
