function f = lhs(k, maxX, minX)

[n d] = size(minX);
if (d == 1)
    minX = reshape(minX, d, n);
    maxX = reshape(maxX, d, n);
end
[n d] = size(minX);

Co = lhsdesign(k, d);   % coeff generated by LHS to be used for params generation

min = repmat(minX, [k 1]);
max = repmat(maxX, [k 1]);
f = min + (max - min).*Co;
%display(f);
end